# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.7
env:
  - DJANGO_VERSION=\>=2.2,\<3.0
  - DJANGO_VERSION=\>=3.0a,\<3.1
install:
  - pip install --upgrade pip
  - pip install --upgrade Django$DJANGO_VERSION
  - pip install -q -e .
  - pip install -q -r requirements.txt
script:
  - coverage run --source djrichtextfield --branch manage.py test
after_success:
  - coveralls
branches:
  only:
    - master
sudo: false
